// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: hdrplusmakernote.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GoogleHDRPlusMakerNote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageInfo     *ImageInfo             `protobuf:"bytes,1,opt,name=image_info,json=imageInfo,proto3" json:"image_info,omitempty"`
	TimeLogText   string                 `protobuf:"bytes,2,opt,name=time_log_text,json=timeLogText,proto3" json:"time_log_text,omitempty"`
	SummaryText   string                 `protobuf:"bytes,3,opt,name=summary_text,json=summaryText,proto3" json:"summary_text,omitempty"`
	FrameCount    *FrameInfo             `protobuf:"bytes,9,opt,name=frame_count,json=frameCount,proto3" json:"frame_count,omitempty"`
	DeviceInfo    *DeviceInfo            `protobuf:"bytes,12,opt,name=device_info,json=deviceInfo,proto3" json:"device_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoogleHDRPlusMakerNote) Reset() {
	*x = GoogleHDRPlusMakerNote{}
	mi := &file_hdrplusmakernote_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoogleHDRPlusMakerNote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleHDRPlusMakerNote) ProtoMessage() {}

func (x *GoogleHDRPlusMakerNote) ProtoReflect() protoreflect.Message {
	mi := &file_hdrplusmakernote_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleHDRPlusMakerNote.ProtoReflect.Descriptor instead.
func (*GoogleHDRPlusMakerNote) Descriptor() ([]byte, []int) {
	return file_hdrplusmakernote_proto_rawDescGZIP(), []int{0}
}

func (x *GoogleHDRPlusMakerNote) GetImageInfo() *ImageInfo {
	if x != nil {
		return x.ImageInfo
	}
	return nil
}

func (x *GoogleHDRPlusMakerNote) GetTimeLogText() string {
	if x != nil {
		return x.TimeLogText
	}
	return ""
}

func (x *GoogleHDRPlusMakerNote) GetSummaryText() string {
	if x != nil {
		return x.SummaryText
	}
	return ""
}

func (x *GoogleHDRPlusMakerNote) GetFrameCount() *FrameInfo {
	if x != nil {
		return x.FrameCount
	}
	return nil
}

func (x *GoogleHDRPlusMakerNote) GetDeviceInfo() *DeviceInfo {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

type ImageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageName     string                 `protobuf:"bytes,1,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	ImageData     []byte                 `protobuf:"bytes,2,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageInfo) Reset() {
	*x = ImageInfo{}
	mi := &file_hdrplusmakernote_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageInfo) ProtoMessage() {}

func (x *ImageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_hdrplusmakernote_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageInfo.ProtoReflect.Descriptor instead.
func (*ImageInfo) Descriptor() ([]byte, []int) {
	return file_hdrplusmakernote_proto_rawDescGZIP(), []int{1}
}

func (x *ImageInfo) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *ImageInfo) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

type FrameInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FrameCount     int32                  `protobuf:"varint,3,opt,name=frame_count,json=frameCount,proto3" json:"frame_count,omitempty"`
	CreateDateInfo *CreateDateInfo        `protobuf:"bytes,36,opt,name=create_date_info,json=createDateInfo,proto3" json:"create_date_info,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FrameInfo) Reset() {
	*x = FrameInfo{}
	mi := &file_hdrplusmakernote_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameInfo) ProtoMessage() {}

func (x *FrameInfo) ProtoReflect() protoreflect.Message {
	mi := &file_hdrplusmakernote_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameInfo.ProtoReflect.Descriptor instead.
func (*FrameInfo) Descriptor() ([]byte, []int) {
	return file_hdrplusmakernote_proto_rawDescGZIP(), []int{2}
}

func (x *FrameInfo) GetFrameCount() int32 {
	if x != nil {
		return x.FrameCount
	}
	return 0
}

func (x *FrameInfo) GetCreateDateInfo() *CreateDateInfo {
	if x != nil {
		return x.CreateDateInfo
	}
	return nil
}

type CreateDateInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreateDate    int64                  `protobuf:"varint,1,opt,name=create_date,json=createDate,proto3" json:"create_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDateInfo) Reset() {
	*x = CreateDateInfo{}
	mi := &file_hdrplusmakernote_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDateInfo) ProtoMessage() {}

func (x *CreateDateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_hdrplusmakernote_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDateInfo.ProtoReflect.Descriptor instead.
func (*CreateDateInfo) Descriptor() ([]byte, []int) {
	return file_hdrplusmakernote_proto_rawDescGZIP(), []int{3}
}

func (x *CreateDateInfo) GetCreateDate() int64 {
	if x != nil {
		return x.CreateDate
	}
	return 0
}

type DeviceInfo struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	DeviceMake             string                 `protobuf:"bytes,1,opt,name=device_make,json=deviceMake,proto3" json:"device_make,omitempty"`
	DeviceModel            string                 `protobuf:"bytes,2,opt,name=device_model,json=deviceModel,proto3" json:"device_model,omitempty"`
	DeviceCodename         string                 `protobuf:"bytes,3,opt,name=device_codename,json=deviceCodename,proto3" json:"device_codename,omitempty"`
	DeviceHardwareRevision string                 `protobuf:"bytes,4,opt,name=device_hardware_revision,json=deviceHardwareRevision,proto3" json:"device_hardware_revision,omitempty"`
	HDRPSoftware           string                 `protobuf:"bytes,6,opt,name=HDRPSoftware,proto3" json:"HDRPSoftware,omitempty"`
	AndroidRelease         string                 `protobuf:"bytes,7,opt,name=AndroidRelease,proto3" json:"AndroidRelease,omitempty"`
	SoftwareDate           int64                  `protobuf:"varint,8,opt,name=SoftwareDate,proto3" json:"SoftwareDate,omitempty"`
	Application            string                 `protobuf:"bytes,9,opt,name=Application,proto3" json:"Application,omitempty"`
	AppVersion             string                 `protobuf:"bytes,10,opt,name=AppVersion,proto3" json:"AppVersion,omitempty"`
	ExposureTimeInfo       *ExposureTimeInfo      `protobuf:"bytes,12,opt,name=exposure_time_info,json=exposureTimeInfo,proto3" json:"exposure_time_info,omitempty"`
	IsoInfo                *ISOInfo               `protobuf:"bytes,13,opt,name=iso_info,json=isoInfo,proto3" json:"iso_info,omitempty"`
	MaxAnalogISO           float32                `protobuf:"fixed32,14,opt,name=MaxAnalogISO,proto3" json:"MaxAnalogISO,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_hdrplusmakernote_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_hdrplusmakernote_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_hdrplusmakernote_proto_rawDescGZIP(), []int{4}
}

func (x *DeviceInfo) GetDeviceMake() string {
	if x != nil {
		return x.DeviceMake
	}
	return ""
}

func (x *DeviceInfo) GetDeviceModel() string {
	if x != nil {
		return x.DeviceModel
	}
	return ""
}

func (x *DeviceInfo) GetDeviceCodename() string {
	if x != nil {
		return x.DeviceCodename
	}
	return ""
}

func (x *DeviceInfo) GetDeviceHardwareRevision() string {
	if x != nil {
		return x.DeviceHardwareRevision
	}
	return ""
}

func (x *DeviceInfo) GetHDRPSoftware() string {
	if x != nil {
		return x.HDRPSoftware
	}
	return ""
}

func (x *DeviceInfo) GetAndroidRelease() string {
	if x != nil {
		return x.AndroidRelease
	}
	return ""
}

func (x *DeviceInfo) GetSoftwareDate() int64 {
	if x != nil {
		return x.SoftwareDate
	}
	return 0
}

func (x *DeviceInfo) GetApplication() string {
	if x != nil {
		return x.Application
	}
	return ""
}

func (x *DeviceInfo) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *DeviceInfo) GetExposureTimeInfo() *ExposureTimeInfo {
	if x != nil {
		return x.ExposureTimeInfo
	}
	return nil
}

func (x *DeviceInfo) GetIsoInfo() *ISOInfo {
	if x != nil {
		return x.IsoInfo
	}
	return nil
}

func (x *DeviceInfo) GetMaxAnalogISO() float32 {
	if x != nil {
		return x.MaxAnalogISO
	}
	return 0
}

type ExposureTimeInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ExposureTimeMin float32                `protobuf:"fixed32,1,opt,name=exposure_time_min,json=exposureTimeMin,proto3" json:"exposure_time_min,omitempty"`
	ExposureTimeMax float32                `protobuf:"fixed32,2,opt,name=exposure_time_max,json=exposureTimeMax,proto3" json:"exposure_time_max,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExposureTimeInfo) Reset() {
	*x = ExposureTimeInfo{}
	mi := &file_hdrplusmakernote_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExposureTimeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExposureTimeInfo) ProtoMessage() {}

func (x *ExposureTimeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_hdrplusmakernote_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExposureTimeInfo.ProtoReflect.Descriptor instead.
func (*ExposureTimeInfo) Descriptor() ([]byte, []int) {
	return file_hdrplusmakernote_proto_rawDescGZIP(), []int{5}
}

func (x *ExposureTimeInfo) GetExposureTimeMin() float32 {
	if x != nil {
		return x.ExposureTimeMin
	}
	return 0
}

func (x *ExposureTimeInfo) GetExposureTimeMax() float32 {
	if x != nil {
		return x.ExposureTimeMax
	}
	return 0
}

type ISOInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsoMin        float32                `protobuf:"fixed32,1,opt,name=iso_min,json=isoMin,proto3" json:"iso_min,omitempty"`
	IsoMax        float32                `protobuf:"fixed32,2,opt,name=iso_max,json=isoMax,proto3" json:"iso_max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ISOInfo) Reset() {
	*x = ISOInfo{}
	mi := &file_hdrplusmakernote_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ISOInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ISOInfo) ProtoMessage() {}

func (x *ISOInfo) ProtoReflect() protoreflect.Message {
	mi := &file_hdrplusmakernote_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ISOInfo.ProtoReflect.Descriptor instead.
func (*ISOInfo) Descriptor() ([]byte, []int) {
	return file_hdrplusmakernote_proto_rawDescGZIP(), []int{6}
}

func (x *ISOInfo) GetIsoMin() float32 {
	if x != nil {
		return x.IsoMin
	}
	return 0
}

func (x *ISOInfo) GetIsoMax() float32 {
	if x != nil {
		return x.IsoMax
	}
	return 0
}

var File_hdrplusmakernote_proto protoreflect.FileDescriptor

const file_hdrplusmakernote_proto_rawDesc = "" +
	"\n" +
	"\x16hdrplusmakernote.proto\x12\x02pb\"\xee\x01\n" +
	"\x16GoogleHDRPlusMakerNote\x12,\n" +
	"\n" +
	"image_info\x18\x01 \x01(\v2\r.pb.ImageInfoR\timageInfo\x12\"\n" +
	"\rtime_log_text\x18\x02 \x01(\tR\vtimeLogText\x12!\n" +
	"\fsummary_text\x18\x03 \x01(\tR\vsummaryText\x12.\n" +
	"\vframe_count\x18\t \x01(\v2\r.pb.FrameInfoR\n" +
	"frameCount\x12/\n" +
	"\vdevice_info\x18\f \x01(\v2\x0e.pb.DeviceInfoR\n" +
	"deviceInfo\"I\n" +
	"\tImageInfo\x12\x1d\n" +
	"\n" +
	"image_name\x18\x01 \x01(\tR\timageName\x12\x1d\n" +
	"\n" +
	"image_data\x18\x02 \x01(\fR\timageData\"j\n" +
	"\tFrameInfo\x12\x1f\n" +
	"\vframe_count\x18\x03 \x01(\x05R\n" +
	"frameCount\x12<\n" +
	"\x10create_date_info\x18$ \x01(\v2\x12.pb.CreateDateInfoR\x0ecreateDateInfo\"1\n" +
	"\x0eCreateDateInfo\x12\x1f\n" +
	"\vcreate_date\x18\x01 \x01(\x03R\n" +
	"createDate\"\xf5\x03\n" +
	"\n" +
	"DeviceInfo\x12\x1f\n" +
	"\vdevice_make\x18\x01 \x01(\tR\n" +
	"deviceMake\x12!\n" +
	"\fdevice_model\x18\x02 \x01(\tR\vdeviceModel\x12'\n" +
	"\x0fdevice_codename\x18\x03 \x01(\tR\x0edeviceCodename\x128\n" +
	"\x18device_hardware_revision\x18\x04 \x01(\tR\x16deviceHardwareRevision\x12\"\n" +
	"\fHDRPSoftware\x18\x06 \x01(\tR\fHDRPSoftware\x12&\n" +
	"\x0eAndroidRelease\x18\a \x01(\tR\x0eAndroidRelease\x12\"\n" +
	"\fSoftwareDate\x18\b \x01(\x03R\fSoftwareDate\x12 \n" +
	"\vApplication\x18\t \x01(\tR\vApplication\x12\x1e\n" +
	"\n" +
	"AppVersion\x18\n" +
	" \x01(\tR\n" +
	"AppVersion\x12B\n" +
	"\x12exposure_time_info\x18\f \x01(\v2\x14.pb.ExposureTimeInfoR\x10exposureTimeInfo\x12&\n" +
	"\biso_info\x18\r \x01(\v2\v.pb.ISOInfoR\aisoInfo\x12\"\n" +
	"\fMaxAnalogISO\x18\x0e \x01(\x02R\fMaxAnalogISO\"j\n" +
	"\x10ExposureTimeInfo\x12*\n" +
	"\x11exposure_time_min\x18\x01 \x01(\x02R\x0fexposureTimeMin\x12*\n" +
	"\x11exposure_time_max\x18\x02 \x01(\x02R\x0fexposureTimeMax\";\n" +
	"\aISOInfo\x12\x17\n" +
	"\aiso_min\x18\x01 \x01(\x02R\x06isoMin\x12\x17\n" +
	"\aiso_max\x18\x02 \x01(\x02R\x06isoMaxB&Z$github.com/ZanyLeonic/exif-reader/pbb\x06proto3"

var (
	file_hdrplusmakernote_proto_rawDescOnce sync.Once
	file_hdrplusmakernote_proto_rawDescData []byte
)

func file_hdrplusmakernote_proto_rawDescGZIP() []byte {
	file_hdrplusmakernote_proto_rawDescOnce.Do(func() {
		file_hdrplusmakernote_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hdrplusmakernote_proto_rawDesc), len(file_hdrplusmakernote_proto_rawDesc)))
	})
	return file_hdrplusmakernote_proto_rawDescData
}

var file_hdrplusmakernote_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_hdrplusmakernote_proto_goTypes = []any{
	(*GoogleHDRPlusMakerNote)(nil), // 0: pb.GoogleHDRPlusMakerNote
	(*ImageInfo)(nil),              // 1: pb.ImageInfo
	(*FrameInfo)(nil),              // 2: pb.FrameInfo
	(*CreateDateInfo)(nil),         // 3: pb.CreateDateInfo
	(*DeviceInfo)(nil),             // 4: pb.DeviceInfo
	(*ExposureTimeInfo)(nil),       // 5: pb.ExposureTimeInfo
	(*ISOInfo)(nil),                // 6: pb.ISOInfo
}
var file_hdrplusmakernote_proto_depIdxs = []int32{
	1, // 0: pb.GoogleHDRPlusMakerNote.image_info:type_name -> pb.ImageInfo
	2, // 1: pb.GoogleHDRPlusMakerNote.frame_count:type_name -> pb.FrameInfo
	4, // 2: pb.GoogleHDRPlusMakerNote.device_info:type_name -> pb.DeviceInfo
	3, // 3: pb.FrameInfo.create_date_info:type_name -> pb.CreateDateInfo
	5, // 4: pb.DeviceInfo.exposure_time_info:type_name -> pb.ExposureTimeInfo
	6, // 5: pb.DeviceInfo.iso_info:type_name -> pb.ISOInfo
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_hdrplusmakernote_proto_init() }
func file_hdrplusmakernote_proto_init() {
	if File_hdrplusmakernote_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hdrplusmakernote_proto_rawDesc), len(file_hdrplusmakernote_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hdrplusmakernote_proto_goTypes,
		DependencyIndexes: file_hdrplusmakernote_proto_depIdxs,
		MessageInfos:      file_hdrplusmakernote_proto_msgTypes,
	}.Build()
	File_hdrplusmakernote_proto = out.File
	file_hdrplusmakernote_proto_goTypes = nil
	file_hdrplusmakernote_proto_depIdxs = nil
}
